### ISSUE TITLE
Dealing with non-ASCII chars

### ISSUE THREAD

**Issue by RobinMeis** [RobinMeis/MITMsmtp#9]
```
Closed connection!
----------------------------------------
Exception happened during processing of request from ('10.2.10.131', 56622)
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/MITMsmtp-0.0.2-py3.5.egg/MITMsmtp/SMTPHandler.py", line 59, in handle
    raise e
  File "/usr/local/lib/python3.5/dist-packages/MITMsmtp-0.0.2-py3.5.egg/MITMsmtp/SMTPHandler.py", line 54, in handle
    self.readMSG()
  File "/usr/local/lib/python3.5/dist-packages/MITMsmtp-0.0.2-py3.5.egg/MITMsmtp/SMTPHandler.py", line 170, in readMSG
    line = self.readLine()
  File "/usr/local/lib/python3.5/dist-packages/MITMsmtp-0.0.2-py3.5.egg/MITMsmtp/SMTPHandler.py", line 23, in readLine
    line = self.rfile.readline().strip()
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 70: ordinal not in range(128)
----------------------------------------

```

**Comment by mazdafunsunn** [comment]
could be related:
![image](https://user-images.githubusercontent.com/3892223/101696463-cfb57c80-3a7e-11eb-9740-4c4105adc0e0.png)

**Comment by RobinMeis** [comment]
@mazdafunsunn Which parameters did you use when starting up MITMsmtp?
